appName:  shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.4.2
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 50051